/**
 * Sanitisation policy for rendered Markdown.
 *
 * A Markdown file is untrusted input. Raw HTML is parsed (so GitHub-style
 * READMEs keep their `<details>`, `<img>` and `<kbd>`) and then forced through
 * this schema before anything reaches the DOM.
 *
 * The policy is the well-tested `hast-util-sanitize` default schema — the same
 * baseline GitHub publishes — widened only where Markdown genuinely needs it.
 * Everything not listed here is removed, notably every `on*` handler and the
 * `style` attribute.
 */

import { defaultSchema } from "rehype-sanitize";
import type { Options as SanitizeSchema } from "rehype-sanitize";

const baseAttributes = defaultSchema.attributes ?? {};

/** Class names our own renderers emit, allowed on top of the defaults. */
const RENDERER_CLASSES = /^(md-|math-|katex|shiki|footnotes|data-footnote)/;

export const sanitizeSchema: SanitizeSchema = {
  ...defaultSchema,

  // `clobberPrefix` is intentionally empty. `mdast-util-to-hast` already
  // prefixes footnote ids and their `#fragment` links with `user-content-`, and
  // the sanitiser would prefix the id a second time while leaving the href
  // alone, breaking every footnote link. Heading ids are generated by our own
  // slugger after this step, and all id lookups in the preview are scoped to
  // its container, so the classic DOM-clobbering vector is not reachable.
  clobberPrefix: "",

  // Scripts and stylesheets can never survive, whatever the attribute rules say.
  strip: ["script", "style", "iframe", "object", "embed", "form"],

  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "figure",
    "figcaption",
    "mark",
    "time",
    "video",
    "audio",
    "track",
    "abbr",
    "center",
  ],

  attributes: {
    ...baseAttributes,

    // `language-*` drives syntax highlighting; `math-inline`/`math-display`
    // mark KaTeX sources. Both come from remark plugins, not from the author.
    code: [
      ["className", /^language-./],
      ["className", /^math-(inline|display)$/],
    ],
    pre: [
      ["className", /^language-/],
      ["className", /^md-/],
    ],
    span: [["className", /^(katex|math-|md-|hljs)/], "title", "ariaHidden"],
    div: [...(baseAttributes.div ?? []), ["className", RENDERER_CLASSES], "align", "dir", "dataLanguage"],
    a: [...(baseAttributes.a ?? []), "rel", "name", ["className", RENDERER_CLASSES], "ariaHidden"],
    img: [
      ...(baseAttributes.img ?? []),
      "loading",
      "decoding",
      "width",
      "height",
      "title",
      "align",
      "className",
    ],
    input: [["type", "checkbox"], ["disabled", true], ["checked", true], "className"],
    details: ["open", ["className", RENDERER_CLASSES]],
    summary: [["className", RENDERER_CLASSES], "ariaLabel"],
    li: [...(baseAttributes.li ?? []), ["className", RENDERER_CLASSES]],
    ul: [...(baseAttributes.ul ?? []), ["className", RENDERER_CLASSES]],
    ol: [...(baseAttributes.ol ?? []), ["className", RENDERER_CLASSES], "start", "reversed"],
    table: [...(baseAttributes.table ?? []), ["className", RENDERER_CLASSES], "align"],
    section: [...(baseAttributes.section ?? []), ["className", RENDERER_CLASSES], "dataFootnotes"],
    video: ["src", "controls", "width", "height", "poster", "loop", "muted", "title"],
    audio: ["src", "controls", "loop", "muted", "title"],
    track: ["src", "kind", "srcLang", "label", "default"],
    figure: [["className", RENDERER_CLASSES]],
    figcaption: [["className", RENDERER_CLASSES]],
    time: ["dateTime"],
    abbr: ["title"],
    mark: [["className", RENDERER_CLASSES]],
  },

  protocols: {
    ...defaultSchema.protocols,
    // `tel:` is a legitimate link target in documentation.
    href: [...(defaultSchema.protocols?.href ?? []), "tel"],
    // Inline `data:` images are common (pasted screenshots). Only image and
    // media resources are served with an `img-src data:` CSP directive, and a
    // `data:` payload inside an `<img>` cannot execute script.
    src: [...(defaultSchema.protocols?.src ?? []), "data"],
  },
};

/**
 * Escape hatch used by the security tests: property names that must never
 * appear in sanitised output.
 */
export const FORBIDDEN_ATTRIBUTES = [
  "onclick",
  "onerror",
  "onload",
  "onmouseover",
  "onfocus",
  "style",
  "formaction",
  "srcdoc",
];
